env:
  dev
server:
  port: 8017
mybatis:
  config-location: classpath:mybatis/mybatis.cfg.xml        # mybatis配置文件所在路径
  type-aliases-package: com.micro.cloud.entity              # 所有Entity别名类所在包
  mapper-locations:
  - classpath:mybatis/mapper/**/*.xml                       # mapper映射文件
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://192.168.0.66:3306/organize_activity?useUnicode=true&characterEncoding=UTF-8&multiStatementAllow=true
    username: root
    password: root
    dbcp2:
      min-idle: 5
      initial-size: 5
      max-total: 5
      max-wait-millis: 200
  redis:
    host: 192.168.0.66
    port: 6379
    password: sdtg26a3
    pool:
      maxActive: 600
      maxWait: 1000
      maxIdle: 300
      minIdle: 0
    timeout: 100000    
  rabbitmq:
    host: 192.168.0.114
    port: 5672
    password: jinghao
    username: jinghao 
#OSS bucket  
bucketName: zzhd-bucket
#Pay 小程序支付参数
xcxpay:
  mch_id: 1531248501
  mchKey: 6764477B2AF94156A94ABCCFE07CC0BD
  key: 6764477B2AF94156A94ABCCFE07CC0BD
  payurl: http://ii.sinelinked.com/tg_pay/pay/unifiedOrder
  queryurl: http://ii.sinelinked.com/tg_pay/pay/queryOrder
  payfororganizerurl: http://ii.sinelinked.com/tg_pay/pay/entPay
  querypayforurl: http://ii.sinelinked.com/tg_pay/pay/queryEntPay
xcxMsg:
  templateId:
    partSuccess: MdNMiO7VsbDXPxcjBEsNAmuoimAEAUZoul1Ku-wc3ZM
    draw: MdNMiO7VsbDXPxcjBEsNAmuoimAEAUZoul1Ku-wc3ZM
  sendUrl: http://ii.sinelinked.com/tg_pay/applet/sendtemplatemsg
smallCode:
  url: https://api.weixin.qq.com/wxa/getwxacodeunlimit?access_token=
withdraw:  
 bankUrl: http://ii.sinelinked.com/tg_pay/pay/payBank 
 bankResultUrl: http://ii.sinelinked.com/tg_pay/pay/queryPayBank 
 changeUrl: http://ii.sinelinked.com/tg_pay/pay/entPay  
 refundUrl: http://ii.sinelinked.com/tg_pay/pay/refund 
 queryRefundUrl: http://ii.sinelinked.com/tg_pay/pay/refundQuery 
 mch_id: 1550590321 
 mchKey: r5ykPQ994Dhw536i2CmhNOyrbPlf1pla 
 key: r5ykPQ994Dhw536i2CmhNOyrbPlf1pla 
