env:
  dev
server:
  port: 8016
mybatis:
  config-location: classpath:mybatis/mybatis.cfg.xml        # mybatis配置文件所在路径
  type-aliases-package: com.micro.cloud.entity              # 所有Entity别名类所在包
  mapper-locations:
  - classpath:mybatis/mapper/**/*.xml                       # mapper映射文件
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://192.168.0.66:3306/universal_card?useUnicode=true&characterEncoding=UTF-8&multiStatementAllow=true
    username: root
    password: root
    dbcp2:
      min-idle: 5
      initial-size: 5
      max-total: 5
      max-wait-millis: 200
  redis:
    host: 192.168.0.66
    port: 6379
    password: sdtg26a3
    pool:
      maxActive: 600
      maxWait: 1000
      maxIdle: 300
      minIdle: 0
    timeout: 100000    
  rabbitmq:
    host: localhost
    port: 5672
    password: guest
    username: guest 
  http: 
    multipart: 
      max-file-size: 200MB
      max-request-size: 200MB
#阿里云ocr识别参数
ocr:
  param:
    host: https://dm-57.data.aliyun.com #
    path: /rest/160601/ocr/ocr_business_card.json
    appcode: b7c21fb310df4d8798a117cb5851bad2
    APP_KEY: 25688441
    APP_SECRET: 1ae2455fa22bfec7227a3fab91c7fb3b
#OSS bucket  
bucketName: tymp-bucket
xcxpay:
  mch_id: 1531248501
  mchKey: 6764477B2AF94156A94ABCCFE07CC0BD
  key: 6764477B2AF94156A94ABCCFE07CC0BD
  paysentredurl: http://ii.sinelinked.com/tg_pay/pay/entPay
  querysentredurl: http://ii.sinelinked.com/tg_pay/pay/queryEntPay
  wxXcxAppId: 123455
