env:
  dev
server:
  port: 7004
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 60000
spring:
  zipkin:
    base-url: http://127.0.0.1:9411
    sender:
      type: web    
  sleuth:
    sampler:
      percentage: 1.0
  
      
ribbon:
  ReadTimeout: 10000
  ConnectTimeout: 10000

zuul:
  sensitive-headers: Access-Control-Allow-Origin
  ignored-headers: Access-Control-Allow-Origin,H-APP-Id,Token,APPToken
#  ignored-services: microcloud-dept #用于屏蔽单个服务
  prefix: /UniversalCards
  ignored-services: "*"   #屏蔽多个服务
  routes:
    api-demo:
      path: /apiDemo/**
      serviceId: demoservice
    api-auth:
      path: /apiAuth/**
      serviceId: authserver
    api-test:
      path: /apiTest/**
      serviceId: test-service
    api-personal:
      path: /apiPersonal/**
      serviceId: personalservice
    api-team:
      path: /apiTeam/**
      serviceId: teamservice
    api-msg:
      path: /apiMsg/**
      serviceId: messageservice
    api-material:
      path: /apiMaterial/**
      serviceId: materialservice
    api-task:
      path: /apiTask/**
      serviceId: taskservice
# ignored-patterns: /**/demo3/**,/**/demo2/**     #禁止访问
  max:
    host:
      connections: 500
  host:
    socket-timeout-millis: 10000
    connect-timeout-millis: 60000  
#zuul自定义异常处理    
  SendErrorFilter:
    post: 
      disable: true  
# log: 
#   loginFlag: true
#   allFlag: true
black:
  url: 192.168.1.1,192.168.1.2,192.168.1.3,127.0.0.1
