env:
  dev
server:
  port: 8021
#mysql日志
logging:
  level:
    com.base.micro.dao: debug
mybatis:
  config-location: classpath:mybatis/mybatis.cfg.xml        # mybatis配置文件所在路径
  type-aliases-package: com.micro.cloud.entity              # 所有Entity别名类所在包
  mapper-locations:
  - classpath:mybatis/mapper/**/*.xml                       # mapper映射文件
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://192.168.0.66:3306/universal_card?useUnicode=true&characterEncoding=UTF-8&multiStatementAllow=true
    username: root
    password: root
    dbcp2:
      min-idle: 5
      initial-size: 5
      max-total: 5
      max-wait-millis: 200
  redis:
    host: 192.168.0.66
    port: 6379
    password: sdtg26a3
    pool:
      maxActive: 600
      maxWait: 1000
      maxIdle: 300
      minIdle: 0
    timeout: 100000
 app:
   quartz:
      scheduler:
        instance-name: welendScheduler
        instance-id: NON_CLUSTERED
        skip-update-check: true
        job-factory:
          class: org.quartz.simpl.SimpleJobFactory
      job-store:
        class: org.quartz.impl.jdbcjobstore.JobStoreTX
        driver-delegate-class: org.quartz.impl.jdbcjobstore.StdJDBCDelegate
        datasource: quartzDataSource
        table-prefix: QRTZ_
        is-clustered: true
      thread-pool:
        class: org.quartz.simpl.SimpleThreadPool
        thread-count: 5
      datasource:
        quartzDataSource:
          driver: ${spring.datasource.driver-class-name}
          url: ${spring.datasource.url}
          user: ${spring.datasource.username}
          password: ${spring.datasource.password}
          maxConnections: 5
          validationQuery: select 0
          connection-provider:
            class: com.developlee.quartz.config.quartz.DruidConnectionProvider
